# http + socks
mixed-port: 2222
allow-lan: false
external-controller: 127.0.0.1:61198
secret: d555cf84-7e14-4a4b-8bea-6ff3d0b073f2

# Rule / Global / Direct (默认为 Rule 模式)
Mode: Rule

proxies:
  - name: SG
    type: vmess
    server: ec2-13-212-14-245.ap-southeast-1.compute.amazonaws.com
    port: 23382
    uuid: 2798f5ac-75d0-424f-be0c-b111080fb32b
    alterId: 0
    cipher: auto
    tls-hostname: huawei.com
    Host: huawei.com
proxy-groups:
  - name: Auto
    type: url-test
    proxies:
      - SG
    url: http://www.gstatic.com/generate_204
    interval: 1200
rules:
# > SELF
  - DST-PORT,22382,DIRECT
# > Google
  - DOMAIN-KEYWORD,google,Auto
  - DOMAIN-KEYWORD,youtube,Auto
  - DOMAIN-SUFFIX,gstatic.com,Auto
# > meta
  - DOMAIN-KEYWORD,facebook,Auto
  - DOMAIN-KEYWORD,instagram,Auto
  - DOMAIN-KEYWORD,whatsapp,Auto
# > Microsoft
  - DOMAIN-KEYWORD,github,Auto
  - DOMAIN-KEYWORD,microsoft,Auto
  - DOMAIN-KEYWORD,live,Auto
  - DOMAIN-KEYWORD,onedrive,Auto
  - DOMAIN-KEYWORD,bing,Auto
  - DOMAIN-KEYWORD,msn,Auto
  - DOMAIN-KEYWORD,windows,Auto
  - DOMAIN-KEYWORD,office,Auto
# > Amazon
  - DOMAIN-KEYWORD,amazon,Auto
# > Baidu  
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
# > Huawei
  - DOMAIN-KEYWORD,huawei,DIRECT
  - DOMAIN-KEYWORD,dbankcdn,DIRECT
  - DOMAIN-KEYWORD,hicloud,DIRECT
# > 360
  - DOMAIN-SUFFIX,360.cn,DIRECT
# > localhost
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
# > GEOIP
  - GEOIP,CN,DIRECT
  - MATCH,Auto
