# http + socks
mixed-port: 2222
allow-lan: false
external-controller: 127.0.0.1:61198
secret: d555cf84-7e14-4a4b-8bea-6ff3d0b073f2

# Rule / Global / Direct (默认为 Rule 模式)
Mode: Rule

proxies:
  - name: SG-TJ-WS
    type: trojan
    server: www.shopmall.live
    port: 443
    password: AofA15SFOd8D0m739epZ5Qf0Z18TweOP
    network: ws
    sni: www.shopmall.live
    skip-cert-verify: true
    udp: true
    ws-opts:
      path: /give-me-more-money
      headers:
        Host: www.shopmall.live
  - name: V2
    type: vmess
    server: 18.143.156.23
    port: 23382
    uuid: 407a6a6c-f6b8-4346-b0bc-6abdcf1dd809
    afterId: 0
    cipher: auto
proxy-groups:
  - name: Auto
    type: url-test
    proxies:
      - V2
      - SG-TJ-WS
    url: http://www.gstatic.com/generate_204
    interval: 1200
rules:
# > SELF
  - DST-PORT,22382,DIRECT
# > Google
  - DOMAIN-KEYWORD,google,Auto
  - DOMAIN-KEYWORD,youtube,Auto
  - DOMAIN-SUFFIX,gstatic.com,Auto
# > Telegram
  - DOMAIN-KEYWORD,telegram,Auto
  - DOMAIN-SUFFIX,t.me,Auto
# > meta
  - DOMAIN-KEYWORD,facebook,Auto
  - DOMAIN-KEYWORD,instagram,Auto
  - DOMAIN-KEYWORD,whatsapp,Auto
# > Microsoft
  - DOMAIN-KEYWORD,github,Auto
  - DOMAIN-KEYWORD,microsoft,Auto
  - DOMAIN-KEYWORD,live,Auto
  - DOMAIN-KEYWORD,onedrive,Auto
  - DOMAIN-KEYWORD,bing,Auto
  - DOMAIN-KEYWORD,msn,Auto
  - DOMAIN-KEYWORD,windows,Auto
  - DOMAIN-KEYWORD,office,Auto
# > Amazon
  - DOMAIN-KEYWORD,amazon,Auto
# > Baidu  
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
# > Huawei
  - DOMAIN-KEYWORD,huawei,DIRECT
  - DOMAIN-KEYWORD,dbankcdn,DIRECT
  - DOMAIN-KEYWORD,hicloud,DIRECT
# > 360
  - DOMAIN-SUFFIX,360.cn,DIRECT
# > localhost
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - DOMAIN-KEYWORD,tokenusdt,DIRECT
# > GEOIP
  - GEOIP,CN,DIRECT
  - MATCH,Auto
